import type {
  Borrower,
  HomeMetrics,
  GrowthSignal,
  ServicingIndicator,
  DSODataPoint,
  PublicRecord,
  Covenant,
  ConcentrationEntry,
  Transaction,
  PersonNode,
  FollowUpEntry,
  CovenantScheduleEntry,
  UtilizationDataPoint,
  IndustryBenchmark,
  RealEstateAsset,
  SOSFiling,
} from "./types";

export const borrowers: Borrower[] = [
  {
    id: "bor-001",
    name: "Apex Manufacturing Corp",
    facilityId: "FAC-2024-0891",
    opportunityScore: 92,
    opportunityTypes: ["Upsell Candidate"],
    signals: [
      { text: "Revenue up 34% YoY", strength: "Strong" },
      { text: "Credit line 85% utilized", strength: "Strong" },
      { text: "New equipment purchase planned", strength: "Moderate" },
    ],
    lastContactDate: "2026-03-28",
    assignedOfficer: "Sarah Martinez",
    currentFacilitySummary: "$5M revolving line, 85% utilized",
    suggestedProduct: "Equipment financing line",
    estimatedUpsellRange: "$1.5M - $2.5M",
    confidenceScore: 87,
    industry: "Manufacturing",
    naicsCode: "332710",
  },
  {
    id: "bor-002",
    name: "Greenfield Logistics LLC",
    facilityId: "FAC-2024-0743",
    opportunityScore: 85,
    opportunityTypes: ["Upsell Candidate", "Restructure Candidate"],
    signals: [
      { text: "DSO improved 18 days", strength: "Strong" },
      { text: "New lien filed by vendor", strength: "Moderate" },
      { text: "Inventory expansion 22%", strength: "Moderate" },
    ],
    lastContactDate: "2026-03-15",
    assignedOfficer: "James Chen",
    currentFacilitySummary: "$3.2M ABL facility, maturing Q3 2026",
    suggestedProduct: "Line of credit increase",
    estimatedUpsellRange: "$800K - $1.2M",
    confidenceScore: 74,
    restructuringTrigger: "Facility maturing in 5 months",
    recommendedAction: "Discuss term extension and line increase",
    riskLevel: "Low",
    industry: "Transportation & Warehousing",
    naicsCode: "484110",
  },
  {
    id: "bor-003",
    name: "Coastal Health Services",
    facilityId: "FAC-2023-1102",
    opportunityScore: 78,
    opportunityTypes: ["Restructure Candidate"],
    signals: [
      { text: "Covenant approaching breach (DSCR)", strength: "Strong" },
      { text: "DSO deteriorating +12 days", strength: "Moderate" },
      { text: "Industry headwinds in healthcare staffing", strength: "Weak" },
    ],
    lastContactDate: "2026-04-01",
    assignedOfficer: "Sarah Martinez",
    currentFacilitySummary: "$8M term loan, 3 years remaining",
    restructuringTrigger: "DSCR covenant at 1.22x vs 1.20x minimum",
    recommendedAction: "Review collateral and discuss covenant amendment",
    riskLevel: "Medium",
    industry: "Healthcare",
    naicsCode: "621111",
  },
  {
    id: "bor-004",
    name: "Summit Steel Distributors",
    facilityId: "FAC-2024-0215",
    opportunityScore: 71,
    opportunityTypes: ["Upsell Candidate"],
    signals: [
      { text: "AR volume up 28% vs prior quarter", strength: "Strong" },
      { text: "New customer acquisition reducing concentration", strength: "Moderate" },
    ],
    lastContactDate: "2026-03-20",
    assignedOfficer: "Michael Rodriguez",
    currentFacilitySummary: "$4.5M revolving line, 62% utilized",
    suggestedProduct: "Increase revolving line",
    estimatedUpsellRange: "$1M - $1.8M",
    confidenceScore: 69,
    industry: "Wholesale Trade",
    naicsCode: "423510",
  },
  {
    id: "bor-005",
    name: "TechVenture Solutions Inc",
    facilityId: "FAC-2025-0033",
    opportunityScore: 67,
    opportunityTypes: ["Restructure Candidate"],
    signals: [
      { text: "Concentration risk: top debtor at 28%", strength: "Strong" },
      { text: "Payment behavior slowing", strength: "Moderate" },
      { text: "Recent lawsuit filed (defendant)", strength: "Weak" },
    ],
    lastContactDate: "2026-02-28",
    assignedOfficer: "James Chen",
    currentFacilitySummary: "$2.8M ABL facility",
    restructuringTrigger: "Concentration risk elevated, single debtor exceeds cap",
    recommendedAction: "Adjust advance rate and review concentration thresholds",
    riskLevel: "High",
    industry: "Information Technology",
    naicsCode: "541511",
  },
  {
    id: "bor-006",
    name: "Prairie Agricultural Co-op",
    facilityId: "FAC-2024-0567",
    opportunityScore: 58,
    opportunityTypes: ["Upsell Candidate"],
    signals: [
      { text: "Seasonal revenue increase expected", strength: "Moderate" },
      { text: "Strong payment history (99% on-time)", strength: "Strong" },
    ],
    lastContactDate: "2026-03-10",
    assignedOfficer: "Sarah Martinez",
    currentFacilitySummary: "$6M seasonal line, 40% utilized",
    suggestedProduct: "Temporary line increase for harvest season",
    estimatedUpsellRange: "$2M - $3M",
    confidenceScore: 62,
    industry: "Agriculture",
    naicsCode: "111100",
  },
];

export const homeMetrics: HomeMetrics = {
  totalHotLeads: 6,
  upsellCount: 4,
  upsellEstimatedValue: 8_500_000,
  restructureCandidates: 3,
  restructureByRisk: { low: 1, medium: 1, high: 1 },
  covenantBreaches: 2,
  facilitiesInBreach: 2,
  concentrationAlerts: 3,
};

// ---- Borrower Detail Mock Data (keyed to bor-001 by default) ----

export const growthSignals: GrowthSignal[] = [
  {
    name: "Revenue Growth",
    strength: "Strong",
    dataPoint: "Revenue up 34% YoY ($12.4M → $16.6M)",
    dateDetected: "2026-03-01",
  },
  {
    name: "Inventory Expansion",
    strength: "Moderate",
    dataPoint: "Inventory levels increased 22% ($1.8M → $2.2M)",
    dateDetected: "2026-02-15",
  },
  {
    name: "New Customer Acquisition",
    strength: "Moderate",
    dataPoint: "3 new debtors added in past 90 days, reducing concentration",
    dateDetected: "2026-03-10",
  },
  {
    name: "Credit Line Utilization",
    strength: "Strong",
    dataPoint: "Line consistently at 80-90% utilization — potential capacity need",
    dateDetected: "2026-01-20",
  },
];

export const servicingIndicators: ServicingIndicator[] = [
  { name: "On-Time Payment Rate", value: "97.3%", status: "healthy", contributesToScore: false },
  { name: "Avg Days Past Due", value: "2.1 days", status: "healthy", contributesToScore: false },
  { name: "Line Utilization", value: "85%", status: "watch", contributesToScore: true },
  { name: "Verification Frequency", value: "Monthly", status: "healthy", contributesToScore: false },
  { name: "Exception Rate (90d)", value: "3 exceptions", status: "watch", contributesToScore: true },
  { name: "Reserve Balance Trend", value: "Stable", status: "healthy", contributesToScore: false },
];

export const utilizationHistory: UtilizationDataPoint[] = [
  { month: "Apr 2025", utilization: 62 },
  { month: "May 2025", utilization: 65 },
  { month: "Jun 2025", utilization: 68 },
  { month: "Jul 2025", utilization: 72 },
  { month: "Aug 2025", utilization: 70 },
  { month: "Sep 2025", utilization: 74 },
  { month: "Oct 2025", utilization: 78 },
  { month: "Nov 2025", utilization: 76 },
  { month: "Dec 2025", utilization: 80 },
  { month: "Jan 2026", utilization: 82 },
  { month: "Feb 2026", utilization: 84 },
  { month: "Mar 2026", utilization: 85 },
];

export const dsoHistory: DSODataPoint[] = [
  { month: "Apr 2024", value: 48, industryAvg: 42 },
  { month: "May 2024", value: 47, industryAvg: 42 },
  { month: "Jun 2024", value: 46, industryAvg: 41 },
  { month: "Jul 2024", value: 45, industryAvg: 41 },
  { month: "Aug 2024", value: 44, industryAvg: 42 },
  { month: "Sep 2024", value: 43, industryAvg: 42 },
  { month: "Oct 2024", value: 44, industryAvg: 41 },
  { month: "Nov 2024", value: 42, industryAvg: 41 },
  { month: "Dec 2024", value: 41, industryAvg: 42 },
  { month: "Jan 2025", value: 40, industryAvg: 42 },
  { month: "Feb 2025", value: 39, industryAvg: 41 },
  { month: "Mar 2025", value: 38, industryAvg: 41 },
  { month: "Apr 2025", value: 38, industryAvg: 41 },
  { month: "May 2025", value: 37, industryAvg: 42 },
  { month: "Jun 2025", value: 36, industryAvg: 41 },
  { month: "Jul 2025", value: 36, industryAvg: 41 },
  { month: "Aug 2025", value: 35, industryAvg: 42 },
  { month: "Sep 2025", value: 35, industryAvg: 42 },
  { month: "Oct 2025", value: 34, industryAvg: 41 },
  { month: "Nov 2025", value: 34, industryAvg: 41 },
  { month: "Dec 2025", value: 33, industryAvg: 42 },
  { month: "Jan 2026", value: 33, industryAvg: 42 },
  { month: "Feb 2026", value: 32, industryAvg: 41 },
  { month: "Mar 2026", value: 31, industryAvg: 41 },
];

export const publicRecords: PublicRecord[] = [
  {
    id: "pr-001",
    type: "Lien",
    filingDate: "2026-03-15",
    jurisdiction: "State of Ohio",
    parties: "IRS vs Apex Manufacturing Corp",
    amount: 45000,
    source: "Ohio Secretary of State UCC Database",
    severity: "Watch",
    description: "Federal tax lien filed — $45,000 outstanding payroll taxes",
  },
  {
    id: "pr-002",
    type: "Lien",
    filingDate: "2026-01-22",
    jurisdiction: "Cuyahoga County, OH",
    parties: "First National Bank — UCC-1 Filing",
    source: "Cuyahoga County Recorder",
    severity: "Informational",
    description: "UCC-1 financing statement — existing equipment lien (expected)",
  },
  {
    id: "pr-003",
    type: "Lawsuit",
    filingDate: "2025-11-08",
    jurisdiction: "Cuyahoga County Court of Common Pleas",
    parties: "Smith & Associates vs Apex Manufacturing Corp",
    amount: 125000,
    source: "Ohio Courts Network",
    severity: "Watch",
    description: "Breach of contract claim — dispute over equipment delivery terms",
  },
];

export const covenants: Covenant[] = [
  {
    id: "cov-001",
    name: "Debt Service Coverage Ratio",
    type: "Financial",
    trackingMode: "Automatic",
    status: "Compliant",
    nextReviewDate: "2026-06-30",
    complianceRule: "GE",
    targetValue: 1.2,
    currentValue: 1.45,
    description: "Borrower must maintain DSCR >= 1.20x",
  },
  {
    id: "cov-002",
    name: "Current Ratio",
    type: "Financial",
    trackingMode: "Automatic",
    status: "Compliant",
    nextReviewDate: "2026-06-30",
    complianceRule: "GE",
    targetValue: 1.5,
    currentValue: 1.82,
    description: "Borrower must maintain Current Ratio >= 1.50x",
  },
  {
    id: "cov-003",
    name: "Leverage Ratio",
    type: "Financial",
    trackingMode: "Automatic",
    status: "Pending",
    nextReviewDate: "2026-06-30",
    complianceRule: "LE",
    targetValue: 3.0,
    currentValue: undefined,
    description: "Total Debt / EBITDA must not exceed 3.0x",
  },
  {
    id: "cov-004",
    name: "Annual Financial Statements",
    type: "Non-Financial",
    trackingMode: "Manual",
    status: "Compliant",
    nextReviewDate: "2026-04-30",
    complianceRule: "EQ",
    targetValue: 1,
    currentValue: 1,
    description: "Audited financial statements due within 120 days of fiscal year end",
  },
  {
    id: "cov-005",
    name: "Minimum Tangible Net Worth",
    type: "Financial",
    trackingMode: "Automatic",
    status: "Non-Compliant",
    nextReviewDate: "2026-06-30",
    complianceRule: "GE",
    targetValue: 2_000_000,
    currentValue: 1_850_000,
    description: "Tangible Net Worth must be >= $2,000,000",
  },
];

export const concentrationData: ConcentrationEntry[] = [
  { debtorName: "National Auto Parts Inc", arBalance: 980000, percentOfBase: 22.5, concentrationCap: 20, status: "Cap Triggered", cappedAmount: 108900 },
  { debtorName: "Midwest Steel Supply", arBalance: 720000, percentOfBase: 16.5, concentrationCap: 20, status: "At Risk", cappedAmount: 0 },
  { debtorName: "Allied Construction Group", arBalance: 540000, percentOfBase: 12.4, concentrationCap: 20, status: "Within Limit", cappedAmount: 0 },
  { debtorName: "Pacific Rim Trading Co", arBalance: 480000, percentOfBase: 11.0, concentrationCap: 20, status: "Within Limit", cappedAmount: 0 },
  { debtorName: "Heartland Distributors", arBalance: 390000, percentOfBase: 9.0, concentrationCap: 20, status: "Within Limit", cappedAmount: 0 },
  { debtorName: "Other (12 debtors)", arBalance: 1_245_000, percentOfBase: 28.6, concentrationCap: 20, status: "Within Limit", cappedAmount: 0 },
];

export const transactions: Transaction[] = [
  { id: "txn-001", date: "2026-04-08", type: "Advance", amount: 250000, runningBalance: 4_250_000, referenceNumber: "ADV-20260408-001", description: "Working capital advance", anomalous: false },
  { id: "txn-002", date: "2026-04-07", type: "Payment", amount: -180000, runningBalance: 4_000_000, referenceNumber: "PMT-20260407-001", description: "Collection applied — National Auto Parts", anomalous: false },
  { id: "txn-003", date: "2026-04-05", type: "Interest", amount: -12500, runningBalance: 4_180_000, referenceNumber: "INT-20260405-001", description: "Monthly interest charge", anomalous: false },
  { id: "txn-004", date: "2026-04-03", type: "Advance", amount: 500000, runningBalance: 4_192_500, referenceNumber: "ADV-20260403-001", description: "Inventory purchase advance", anomalous: true },
  { id: "txn-005", date: "2026-04-01", type: "Fee", amount: -2500, runningBalance: 3_692_500, referenceNumber: "FEE-20260401-001", description: "Monthly facility fee", anomalous: false },
  { id: "txn-006", date: "2026-03-29", type: "Payment", amount: -320000, runningBalance: 3_695_000, referenceNumber: "PMT-20260329-001", description: "Collection applied — Midwest Steel", anomalous: false },
  { id: "txn-007", date: "2026-03-27", type: "Advance", amount: 175000, runningBalance: 4_015_000, referenceNumber: "ADV-20260327-001", description: "Working capital advance", anomalous: false },
  { id: "txn-008", date: "2026-03-25", type: "Adjustment", amount: -15000, runningBalance: 3_840_000, referenceNumber: "ADJ-20260325-001", description: "Ineligible AR adjustment", anomalous: false },
];

export const orgChart: PersonNode[] = [
  { id: "p-001", name: "Robert Chen", title: "CEO & Founder", email: "rchen@apexmfg.com", phone: "(216) 555-0101", isGuarantor: true },
  { id: "p-002", name: "Lisa Patel", title: "CFO", email: "lpatel@apexmfg.com", phone: "(216) 555-0102", isGuarantor: true, reportsTo: "p-001" },
  { id: "p-003", name: "David Kim", title: "VP Operations", email: "dkim@apexmfg.com", phone: "(216) 555-0103", isGuarantor: false, reportsTo: "p-001" },
  { id: "p-004", name: "Maria Santos", title: "Controller", email: "msantos@apexmfg.com", phone: "(216) 555-0104", isGuarantor: false, reportsTo: "p-002" },
  { id: "p-005", name: "James Wright", title: "VP Sales", email: "jwright@apexmfg.com", isGuarantor: false, reportsTo: "p-001" },
];

export const followUpHistory: FollowUpEntry[] = [
  {
    id: "fu-001",
    contactDate: "2026-03-28",
    method: "Call",
    outcome: "Interested",
    notes: "Discussed potential equipment financing. CEO mentioned new production line planned for Q3. Sending term sheet.",
    nextAction: "Send equipment financing term sheet",
    nextActionDueDate: "2026-04-02",
  },
  {
    id: "fu-002",
    contactDate: "2026-03-10",
    method: "Email",
    outcome: "Scheduled Meeting",
    notes: "Sent portfolio review summary. CFO responded — scheduled in-person meeting.",
    nextAction: "Prepare portfolio review deck",
    nextActionDueDate: "2026-03-25",
  },
];

export const covenantSchedule: CovenantScheduleEntry[] = [
  { id: "cs-001", covenantId: "cov-001", covenantName: "Debt Service Coverage Ratio", period: "Q1 2026", status: "Compliant", actualValue: 1.45, targetValue: 1.2, dueDate: "2026-05-15", daysRemaining: 36, notes: "Reviewed — strong cash flow" },
  { id: "cs-002", covenantId: "cov-002", covenantName: "Current Ratio", period: "Q1 2026", status: "Compliant", actualValue: 1.82, targetValue: 1.5, dueDate: "2026-05-15", daysRemaining: 36 },
  { id: "cs-003", covenantId: "cov-003", covenantName: "Leverage Ratio", period: "Q1 2026", status: "Pending", targetValue: 3.0, dueDate: "2026-05-15", daysRemaining: 36, notes: "Awaiting audited financials" },
  { id: "cs-004", covenantId: "cov-005", covenantName: "Minimum Tangible Net Worth", period: "Q1 2026", status: "Non-Compliant", actualValue: 1_850_000, targetValue: 2_000_000, dueDate: "2026-05-15", daysRemaining: 36, notes: "Below threshold — waiver under discussion" },
  { id: "cs-005", covenantId: "cov-001", covenantName: "Debt Service Coverage Ratio", period: "Q2 2026", status: "Pending", targetValue: 1.2, dueDate: "2026-08-15", daysRemaining: 128 },
  { id: "cs-006", covenantId: "cov-004", covenantName: "Annual Financial Statements", period: "FYE 2025", status: "Overdue", targetValue: 1, dueDate: "2026-04-01", daysRemaining: -8, notes: "Auditor delayed — extension requested" },
];

export const industryBenchmarks: IndustryBenchmark[] = [
  { metric: "Days Sales Outstanding", borrowerValue: "31 days", industryAvg: "41 days", comparison: "above" },
  { metric: "Revenue Growth (YoY)", borrowerValue: "34%", industryAvg: "8%", comparison: "above" },
  { metric: "Current Ratio", borrowerValue: "1.82x", industryAvg: "1.65x", comparison: "above" },
  { metric: "Debt-to-EBITDA", borrowerValue: "2.4x", industryAvg: "2.8x", comparison: "above" },
  { metric: "Operating Margin", borrowerValue: "12.1%", industryAvg: "9.4%", comparison: "above" },
];

export const realEstateAssets: RealEstateAsset[] = [
  {
    address: "4500 Industrial Blvd, Cleveland, OH 44135",
    parcelId: "CUY-44135-0891",
    estimatedValue: 3_200_000,
    lastAppraisalDate: "2025-08-15",
    lastAppraisalValue: 3_050_000,
    valueTrend: "appreciation",
    lienPosition: "1st",
    ltv: 62,
  },
  {
    address: "1200 Warehouse Dr, Akron, OH 44301",
    parcelId: "SUM-44301-1204",
    estimatedValue: 1_800_000,
    lastAppraisalDate: "2025-06-01",
    lastAppraisalValue: 1_750_000,
    valueTrend: "stable",
    lienPosition: "1st",
    ltv: 71,
  },
];

export const sosFiling: SOSFiling = {
  entityName: "Apex Manufacturing Corp",
  entityStatus: "Active",
  registeredAgent: "CT Corporation System",
  annualReportStatus: "Filed",
  annualReportDueDate: "2026-07-01",
  recentChanges: ["Registered agent updated (2025-09-12)", "Annual report filed (2025-07-15)"],
};
